version: "3.9"
volumes:
  data:
  grafana:
services:
  grafana:
    image: docker.io/grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
    ports:
     - '3000:3000'
  db:
    image: docker.io/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
networks:
  network-grafana: # Définition d'un réseau personnalisé
    driver: bridge # Type de réseau
