{
 "title": "Amelie",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Query_annee",
    "label": "Année",
    "query": "SELECT annee FROM mydatabase.data_ameli "
   },
   {
    "name": "Query_group_patho",
    "label": "pathologie générale",
    "query": "SELECT patho_niv1 FROM mydatabase.data_ameli "
   }
  ]
 },
 "panels": [
  {
   "title": "Description des Données générales",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "mydatabase",
     "rawSql": "SELECT AVG(montant_moy), COUNT(DISTINCT(top)), COUNT(DISTINCT(annee)), SUM(montant) FROM mydatabase.data_ameli LIMIT 50 "
    }
   ]
  },
  {
   "title": "Montant des remboursements et nombre d'acte par an",
   "type": "trend",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "mydatabase",
     "rawSql": "SELECT SUM(montant), annee, SUM(Ntop) FROM mydatabase.data_ameli GROUP BY annee LIMIT 50 "
    }
   ]
  },
  {
   "title": "Classe d'age et remboursement en $Query_annee",
   "type": "barchart",
   "description": "Compare les montants totaux par classe d'age ainsi que la population française.\n",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 4 },
   "targets": [
    {
     "dataset": "mydatabase",
     "rawSql": "SELECT cla_age_5, SUM(montant), AVG(pop), annee FROM mydatabase.data_ameli WHERE annee = $Query_annee  GROUP BY cla_age_5, annee LIMIT 50 "
    }
   ]
  },
  {
   "title": "Nombre de patient par groupe d'age et le montant remboursé en $Query_annee.  pathologie : $Query_group_patho",
   "type": "barchart",
   "description": "Compare le nombre de patient, leur nombre et le montant total de leur prestation.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 12 },
   "targets": [
    {
     "dataset": "mydatabase",
     "rawSql": "SELECT annee, patho_niv1, cla_age_5, SUM(`nb_traités_pathologie_OK_class_age`), SUM(`montant par classe d'age`) FROM mydatabase.data_ameli WHERE (annee = $Query_annee  AND patho_niv1 = \"$Query_group_patho\") GROUP BY cla_age_5 LIMIT 50 "
    }
   ]
  }
 ]
}